/* eslint key-spacing: off  */

module.exports = {
  'asciidoc':           { 'ext': 'asciidoc' },
  'beamer':             { 'ext': 'tex' },
  'context':            { 'ext': 'tex' },
  'docbook':            { 'ext': 'xml' },
  'docx':               { 'ext': 'docx' },
  'dzslides':           { 'ext': 'html' },
  'epub':               { 'ext': 'epub' },
  'epub3':              { 'ext': 'epub' },
  'fb2':                { 'ext': 'fb2' },
  'html':               { 'ext': 'html' },
  'html5':              { 'ext': 'html' },
  'icml':               { 'ext': 'icml' },
  'json':               { 'ext': 'json' },
  'latex':              { 'ext': 'tex' },
  'man':                { 'ext': 'man' },
  'markdown':           { 'ext': 'md' },
  'markdown_github':    { 'ext': 'md' },
  'markdown_mmd':       { 'ext': 'md' },
  'markdown_phpextra':  { 'ext': 'md' },
  'markdown_strict':    { 'ext': 'md' },
  'mediawiki':          { 'ext': 'txt' },
  'native':             { 'ext': 'hs' },
  'odt':                { 'ext': 'odt' },
  'opendocument':       { 'ext': 'odf' },
  'opml':               { 'ext': 'opml' },
  'org':                { 'ext': 'org' },
  // 'pdf':                { 'ext': 'pdf', 'format': 'latex' },
  'pptx':               { 'ext': 'pptx'},
  'plain':              { 'ext': 'txt' },
  'revealjs':           { 'ext': 'html' },
  'rst':                { 'ext': 'rst' },
  'rtf':                { 'ext': 'rtf' },
  's5':                 { 'ext': 'html' },
  'slideous':           { 'ext': 'html' },
  'slidy':              { 'ext': 'html' },
  'texinfo':            { 'ext': 'texi' },
  'textile':            { 'ext': 'textile' }
}
